### PR TITLE
Version Bump to 3.3.2 / 1.041 + Fix for c++17 on MacOS

### PR DESCRIPTION
**Pull request by davidrohr**
Bumped fastjet to 3.3.2
Bumped fjcontrib to 1.041
Remove a deprecated interface, which is not correctly disabled during configure step on MacOS

### CODE REVIEW

**Comment by davidrohr** [comment]
For me, this builds correctly on Linux and MacOS with C++17 both O2 and AliRoot.
But the new fastjet version breaks AliPhysics. It seems something has changed in the Recluster class.
The failure is only in the EMCALJetTasks.

It seems there is no a Recluster class inside fastjet (tools/Recluster.hh) and one inside jfcontrib (contrib/Recluster.hh).
Recluster is no longer included automatically, but even after I add contrib/Recluster.hh to FJ_include.h in AliPhysics, the problem is that
void fastjet::contrib::RecursiveSymmetryCutBase::set_reclustering(bool, const fastjet::Recluster*)
expects the Recluster class from fastjet and not the one from fjcontrib.

@dberzano @sawenzel: Who would be the person to look into this? I am not familiar with fastjet at all.

**Comment by davidrohr** [comment]
@dberzano : the AliPhysics issue is fixed, and independently we have decided to stick with the old fastjet for non-O2 defaults to be on the safe side. I.e. this can be merged. After merging, there should be a new tag created: "v3.3.2_1.041"

**Comment by dberzano** [comment]
I will take this commit and merge it to the appropriate branch (not master), tagging as well.

**Comment by dberzano** [comment]
(Will reshuffle the master.)

**Pull request merged**
